# Generated by Django 2.1.7 on 2019-04-19 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20190419_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
    ]
